import Head from 'next/head';
import {AiFillLinkedin, AiFillGithub} from "react-icons/ai";
import Image from 'next/image';
import athi from "../public/my-picture-removebg-preview.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Athenkosi Nomavila Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=' bg-white px-10'>
        <section className=' bg-blue-500 h-screen'>
          <div className=' bg-white text-center p-10'>
            <h1 className=' text-5xl py-2 text-blue-600 font-medium'>Athenkosi Nomavila</h1>
            <h2 className=' text-2xl py-2'>Growing Developer.</h2>
            <p className=' text-md py-5 leading-6 text-gray-800'>
              I am doing my final year at WeThinkCode,
              originally from the Eastern Cape.
              Currently also a Tech mentor to the 1st years
              at WeThinkCode. I also play cricket on the weekends.
            </p>
            <p className=' text-md py-5 leading-6 text-gray-800'>
              I want to develop for SovTech cause, it is
              a super great company I feel I can grow and up skill
              myself and provide value to the company not only by
              my technical skils but also with my people's person
              skill. To make sure whoever I talk to or I am in contact
              with leaves our interactions still feeling like the matter.
            </p>
          </div>
          <div className='text-4xl flex justify-center gap-15 py-5 text-gray-800'>
          <a href="https://github.com/Athenksoi-Nomavila">
             <AiFillGithub/>
          </a>

          <a href="https://www.linkedin.com/in/athenkosi-nomavila">
              <AiFillLinkedin />
          </a>
            
            
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-white rounded-full w-80 h-80 overflow-hidden'>
            <Image src={athi}/>
          </div>
        </section>
      </main>

    </div>
  );
}
